version: "3.8"

services:
  diploma-bachelor-core:
    build:
      context: ./
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    privileged: true
    cap_add:
      - SYS_ADMIN
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
