# For testing purposes only

# =================================================================
#
#   MODULE: docker-compose:docker-compose
#   LOCAL ENTRY POINT: .
#
#   extern
#   |-- docker-compose.yml *CURRENT*
#   |-- Dockerfile
#   |-- server.py
#   |-- server.sh
#
#   COMMENT: compose rules for the test server
#
# =================================================================

version: '3'

services:
  diploma-bachelor:
    image: diploma-bachelor-server
    ports:
      - "4723:4723"
    build:
      context: .
      dockerfile: ./Dockerfile
