# For testing purposes only

# =================================================================
#
#   MODULE: docker-compose:docker-compose
#   LOCAL ENTRY POINT: .
#
#   extern
#   |-- docker-compose.yml *CURRENT*
#   |-- Dockerfile
#   |-- server.py
#   |-- server.sh
#
#   COMMENT: compose rules for the test server
#
# =================================================================

version: '3'

services:
  diploma-bachelor-server:
    build:
      context: ./
    ports:
      - "4723:4723"

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
